name: ğŸ”¬ Checks
on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  website-remix-codegen:
    name: ğŸ“¦ Website Remix Codegen
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: |
          yarn --cwd apps/website-remix build:css --minify
          yarn --cwd apps/website-remix build:icons --minify
          yarn --cwd apps/website-remix build:theme

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: website-remix-codegen
          path: apps/website-remix/src/generated

  build-prisma:
    name: ğŸ“¦ Build prisma
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd api build:prisma

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

  build-shared:
    name: ğŸ“¦ Build shared
    runs-on: ubuntu-latest
    needs: build-prisma
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ“¦ Build
        run: yarn --cwd shared clean-build

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: shared-build
          path: shared/build

  lint:
    name: ğŸ”¬ Lint
    runs-on: ubuntu-latest
    needs:
      - build-shared
      - website-remix-codegen
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build
          path: shared/build

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: website-remix-codegen
          path: apps/website-remix/src/generated

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ”¬ Lint
        run: yarn lint

  build-api:
    name: ğŸ“¦ Build API
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build
          path: shared/build

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ“¦ build
        run: yarn --cwd api clean-build

  build-website:
    name: ğŸ“¦ Build Website
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build
          path: shared/build

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ“¦ Build
        run: yarn --cwd apps/website clean-build

  build-website-remix:
    name: ğŸ“¦ Build Website Remix
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build
          path: shared/build

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ“¦ Build
        run: yarn --cwd apps/website-remix clean-build

  build-faune:
    name: ğŸ“¦ Build Faune
    runs-on: ubuntu-latest
    needs: build-shared
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build
          path: shared/build

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: prisma-build
          path: node_modules/.prisma

      - name: ğŸ“¦ Build
        run: yarn --cwd apps/faune clean-build
