name: ğŸ”¬ Checks
on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  lint:
    name: ğŸ”¬ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build prisma
        run: yarn --cwd ./api build:prisma

      - name: ğŸ“¦ Build shared
        run: yarn --cwd ./shared clean-build

      - name: ğŸ“¦ Build faune remix codegen
        run: |
          yarn --cwd ./apps/faune-remix build:css --minify
          yarn --cwd ./apps/faune-remix build:icons --minify
          yarn --cwd ./apps/faune-remix build:theme

      - name: ğŸ“¦ Build website codegen
        run: |
          yarn --cwd ./apps/website build:css --minify
          yarn --cwd ./apps/website build:icons --minify
          yarn --cwd ./apps/website build:theme

      - name: ğŸ“¦ Build show codegen
        run: |
          yarn --cwd ./apps/show build:css --minify
          yarn --cwd ./apps/show build:icons --minify
          yarn --cwd ./apps/show build:theme

      - name: ğŸ”¬ Lint
        run: yarn lint

      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: shared-build
          path: |
            ./node_modules/.prisma
            ./apps/faune-remix/src/generated
            ./apps/website/src/generated
            ./apps/show/src/generated
            ./shared/build

  build-api:
    name: ğŸ“¦ Build API
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build

      - name: ğŸ“¦ build
        run: yarn --cwd ./api clean-build

  build-faune-remix:
    name: ğŸ“¦ Build Faune Remix
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/faune-remix clean-build

  build-website:
    name: ğŸ“¦ Build Website
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/website clean-build

  build-show:
    name: ğŸ“¦ Build Show
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/show clean-build

  build-faune:
    name: ğŸ“¦ Build Faune
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: â¬‡ï¸ Download artifact
        uses: actions/download-artifact@master
        with:
          name: shared-build

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/faune clean-build
