name: ğŸ”¬ Checks
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ğŸ”¬ Lint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ”¬ Lint
        run: yarn lint

  build-api:
    name: ğŸ“¦ Build API
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd ./api clean-build

  build-faune-remix:
    name: ğŸ“¦ Build Faune Remix
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/faune-remix clean-build

  build-website:
    name: ğŸ“¦ Build Website
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/website clean-build

  build-show:
    name: ğŸ“¦ Build Show
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/show clean-build

  build-faune:
    name: ğŸ“¦ Build Faune
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build
        run: yarn --cwd ./apps/faune clean-build
