name: ğŸš€ Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: ğŸ”¬ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1

      - name: ğŸ“¦ Build prisma
        run: yarn --cwd api build:prisma

      - name: ğŸ“¦ Build shared
        run: yarn --cwd shared clean-build

      - name: ğŸ”¬ Lint
        run: yarn lint

  build-api:
    name: ğŸ“¦ Build API
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "api/fly.toml"
          field: "app"

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Setup cache
      - name: âš¡ï¸ Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-api-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: ğŸ”‘ Fly Registry Auth
        uses: docker/login-action@v1
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}

      - name: ğŸ³ Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-api-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-api-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: ğŸšš Move cache
        run: |
          rm -rf /tmp/.buildx-api-cache
          mv /tmp/.buildx-api-cache-new /tmp/.buildx-api-cache

  build-website:
    name: ğŸ“¦ Build Website
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "apps/website/fly.toml"
          field: "app"

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Setup cache
      - name: âš¡ï¸ Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-website-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: ğŸ”‘ Fly Registry Auth
        uses: docker/login-action@v1
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}

      - name: ğŸ³ Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/website/Dockerfile
          push: true
          tags: registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-website-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-website-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: ğŸšš Move cache
        run: |
          rm -rf /tmp/.buildx-website-cache
          mv /tmp/.buildx-website-cache-new /tmp/.buildx-website-cache

  build-faune:
    name: ğŸ“¦ Build Faune
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "apps/faune/fly.toml"
          field: "app"

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Setup cache
      - name: âš¡ï¸ Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-faune-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: ğŸ”‘ Fly Registry Auth
        uses: docker/login-action@v1
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}

      - name: ğŸ³ Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/faune/Dockerfile
          push: true
          tags: registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-faune-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-faune-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: ğŸšš Move cache
        run: |
          rm -rf /tmp/.buildx-faune-cache
          mv /tmp/.buildx-faune-cache-new /tmp/.buildx-faune-cache

  deploy-api:
    name: ğŸš€ Deploy API
    runs-on: ubuntu-latest
    needs: [lint, build-api, build-website, build-faune]
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "api/fly.toml"
          field: "app"

      - name: ğŸš€ Deploy Production
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --config api/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-website:
    name: ğŸš€ Deploy Website
    runs-on: ubuntu-latest
    needs: [lint, build-api, build-website, build-faune]
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "apps/website/fly.toml"
          field: "app"

      - name: ğŸš€ Deploy Production
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --config apps/website/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-faune:
    name: ğŸš€ Deploy Faune
    runs-on: ubuntu-latest
    needs: [lint, build-api, build-website, build-faune]
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "apps/faune/fly.toml"
          field: "app"

      - name: ğŸš€ Deploy Production
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --config apps/faune/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
